<template>
  <div>
    <v-card elevation="2">
      <v-card-title>
        <h3>Status</h3>
      </v-card-title>
      <v-card-text>
        <ul>
          <li>Date: {{ date }}</li>
          <li>Duration: {{ duration }}</li>
          <li>Parsed recipes: {{ recipes.length }}</li>
          <li>Up-to-date recipes: {{ upToDateRecipes.length }}</li>
          <li>Updatable recipes: {{ updatableRecipes.length }}</li>
          <ul>
            <li>Auto-updatable recipes: {{ autoUpdatableRecipes.length }}</li>
            <li>Recipes with a PR already opened: {{ recipesWithPrOpened.length }}</li>
            <li>Recipes with error: {{ updatableRecipesWithError.length }}</li>
          </ul>
          <li>Inconsistent recipes: {{ inconsistentRecipes.length }}</li>
          <li>Unsupported recipes: {{ unsupportedRecipes.length }}</li>
        </ul>
      </v-card-text>

      <v-card-text>
        <p>
          The recipe updatability data and the updated branches are auto-generated by
          <a
            href="https://github.com/qchateau/conan-center-bot"
          >Conan Center Bot</a>.
        </p>
        <p>Any help improving this tool is welcome !</p>
      </v-card-text>
    </v-card>
  </div>
</template>

<script>
export default {
  data () {
    return {
    }
  },
  computed: {
    date () {
      let date = new Date(this.$recipes.status.date)
      return date.toLocaleString('en-GB', {timeZoneName: 'short'})
    },
    recipes () {
      return this.$recipes.status.recipes
    },
    upToDateRecipes () {
      return this.recipes.filter(x => x.up_to_date)
    },
    updatableRecipes () {
      return this.recipes.filter(x => x.updatable)
    },
    autoUpdatableRecipes () {
      return this.updatableRecipes.filter(x =>
        x.updated_branch.owner &&
        x.updated_branch.repo &&
        x.updated_branch.branch
      )
    },
    recipesWithPrOpened () {
      return this.updatableRecipes.filter(x => x.prs_opened.length > 0)
    },
    updatableRecipesWithError () {
      return this.updatableRecipes.filter(x => x.test_error)
    },
    inconsistentRecipes () {
      return this.recipes.filter(x => x.inconsistent_versioning)
    },
    unsupportedRecipes () {
      return this.recipes.filter(x => !x.supported)
    },
    duration () {
      let seconds = this.$recipes.status.duration
      let hours = Math.floor(seconds / 3600)
      seconds -= hours * 3600
      let minutes = Math.floor(seconds / 60)
      seconds -= minutes * 60

      if (hours > 0) {
        return `${hours}h ${minutes}m`
      }
      if (minutes > 0) {
        return `${minutes}m ${Math.round(seconds)}s`
      }

      return `${seconds.toFixed(1)}s`
    }
  }
}
</script>

<style scoped>
</style>
